CREATE TABLE IF NOT EXISTS posts
(
    id    BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    title varchar(256) NOT NULL,
    text  text,
    image bytea,
    likes int DEFAULT 0
);

CREATE TABLE IF NOT EXISTS comments
(
    id      BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    post_id bigint NOT NULL,
    text    text   NOT NULL,
    FOREIGN KEY (post_id)
        REFERENCES posts (id)
        ON DELETE CASCADE
);

CREATE TABLE IF NOT EXISTS tags
(
    tag varchar(30) PRIMARY KEY
);


CREATE TABLE IF NOT EXISTS post_tags
(
    post_id BIGINT REFERENCES posts ON DELETE CASCADE,
    tag_id  VARCHAR REFERENCES tags,
    PRIMARY KEY (post_id, tag_id)
);

INSERT INTO posts VALUES
                      (default, 'newArticle4', 'tetetetetete', NULL, default);

INSERT INTO tags VALUES
    ('tag');

INSERT INTO post_tags VALUES
                      (1, 'tag');

SELECT * FROM posts
JOIN post_tags on posts.id = post_tags.post_id AND post_tags.tag_id='tag';

INSERT INTO comments VALUES
                      (default, 1, 'nice!');

SELECT * FROM comments
    where comments.post_id = 1
