SET MODE PostgreSQL;

DROP TABLE IF EXISTS posts, comments, tags, post_tags;

CREATE TABLE IF NOT EXISTS posts
(
    id    BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    title varchar(256) NOT NULL,
    text  text,
    image bytea,
    likes int DEFAULT 0
);

CREATE TABLE IF NOT EXISTS comments
(
    id      BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    post_id bigint NOT NULL,
    text    text   NOT NULL,
    FOREIGN KEY (post_id)
        REFERENCES posts (id)
        ON DELETE CASCADE
);

CREATE TABLE IF NOT EXISTS tags
(
    tag varchar(30) PRIMARY KEY
);


CREATE TABLE IF NOT EXISTS post_tags
(
    post_id BIGINT REFERENCES posts ON DELETE CASCADE,
    tag_id  VARCHAR REFERENCES tags,
    PRIMARY KEY (post_id, tag_id)
);

CREATE TRIGGER IF NOT EXISTS auto_delete_tags
    AFTER DELETE ON post_tags
    FOR EACH ROW CALL "org.example.utils.DeleteRedundantTagsTrigger";

CREATE TRIGGER IF NOT EXISTS auto_create_tags
    BEFORE INSERT ON post_tags
    FOR EACH ROW CALL "org.example.utils.CreateNewTagsTrigger";


INSERT INTO posts (title, text, image, likes)
VALUES ('Test Post One', 'Why did the goose cross the road?', x'89504E470D0A1A0A', 3);
INSERT INTO posts (title, text, image, likes)
VALUES ('Test Post Two', 'To get to the other side!', x'FFD8FFE000104A464946', 4);
INSERT INTO posts (title, text, image, likes)
VALUES ('Test Post Three', 'Oh, i think it was chicken', x'89504E470D0A1A0A', 5);
INSERT INTO posts (title, text, image, likes)
VALUES ('Test Post Four', 'Anyway...', x'FFD8FFE000104A464946', -7);
INSERT INTO posts (title, text, image, likes)
VALUES ('Test Post Five', 'Gooses a way netter than chicken', x'89504E470D0A1A0A', 9);
INSERT INTO posts (title, text, image, likes)
VALUES ('Test Post Six', 'Oh, hi Mark!', x'FFD8FFE000104A464946', 0);

INSERT INTO comments (post_id, text)
VALUES (1, 'nice!');
INSERT INTO comments (post_id, text)
VALUES (1, 'nice2!');
INSERT INTO comments (post_id, text)
VALUES (2, 'so what about that goose...');

INSERT INTO post_tags (post_id, tag_id)
VALUES (1, 'Goose');
INSERT INTO post_tags (post_id, tag_id)
VALUES (1, 'Road');

INSERT INTO post_tags (post_id, tag_id)
VALUES (2, 'Other');
INSERT INTO post_tags (post_id, tag_id)
VALUES (2, 'Side');
INSERT INTO post_tags (post_id, tag_id)
VALUES (2, 'Get');

INSERT INTO post_tags (post_id, tag_id)
VALUES (3, 'Other');
INSERT INTO post_tags (post_id, tag_id)
VALUES (4, 'Side');
INSERT INTO post_tags (post_id, tag_id)
VALUES (5, 'Get');